### ISSUE TITLE
Organizing Task: Submission Questions Feature

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1627]
This task is to help guide @9921622 on how to approach and continue the implementation of the Submission Questions feature.  This feature was almost completed last summer, but we couldn't quite get it into production in time for the school year.

Please complete these tasks, and comment below when each step is completed:

- [ ] Carefully read through issue #1304 which describes the problem and the feature we plan to implement to solve the problem.  Read through all the discussion, and ask questions about anything that isn't clear.
- [ ] Carefully read through the description provided in PR #1476, including the discussion and resolved review comments
- [ ] Check out the PR locall so you can run it and commit to it: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally
- [ ] Resolve current conflicts in the PR (small conflict based on a recent change you did. I think you should be able to refactor the PR code without much trouble. and Push a commit to the PR.
- [ ] Do a full review of the PR:
    - [ ]  Look through the code using the Review feature in github.
    - [ ] Run the PR branch locally and test it manually, try to break it by doing stuff (creating comment, replying to comments, refreshing at weird times, hitting the back arrow on browser, commenting as a teacher, or as a student, etc. etc.)
    - [ ] Test the migration process (since this changes the DB significantly.  Delete your db container and recreate it form the existing develop branch, change branches and run, ensure things don't break with the migration.  What happens to existing comments?
- [ ] Approve the PR (via your review) when satisfied.

PR #1476 is a transitionary PR, that shouldn't change anything from a user's perspective, but lets us carefully change the db structure for comments in the background, so that we can then implement the actual feature, which exists at WIP PR #1451

Please ask lots of questions!

**Comment by 9921622** [comment]
- [x] Carefully read through issue https://github.com/bytedeck/bytedeck/issues/1304 which describes the problem and the feature we plan to implement to solve the problem. Read through all the discussion, and ask questions about anything that isn't clear.
- [x] Carefully read through the description provided in PR https://github.com/bytedeck/bytedeck/pull/1476, including the discussion and resolved review comments
- [x] Check out the PR locall so you can run it and commit to it: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally
- [x] Resolve current conflicts in the PR (small conflict based on a recent change you did. I think you should be able to refactor the PR code without much trouble. and Push a commit to the PR. 
-- #1632
- [ ] Do a full review of the PR
  - [x]  Look through the code using the Review feature in github. 
  - [x]  Run the PR branch locally and test it manually, try to break it by doing stuff (creating comment, replying to comments, refreshing at weird times, hitting the back arrow on browser, commenting as a teacher, or as a student, etc. etc.)
  - [ ] Test the migration process (since this changes the DB significantly. Delete your db container and recreate it form the existing develop branch, change branches and run, ensure things don't break with the migration. What happens to existing comments?
- [ ] Approve the PR (via your review) when satisfied.
