### ISSUE TITLE
AWS Migration - todo list

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#613]
- [ ] RDS - Postgres
- [ ] Amazon DNS (Route 53)
- [ ] Auto renewal of Let's Encrypt wildcard cert (supported by Amazon Route 53
- [ ] Nginx containered
- [ ] Continuous/Automated Deployment?
- [ ] Staging
